### ISSUE TITLE
Updating an entry

### ISSUE THREAD

**Issue by Rias500** [craftcms/guest-entries#30]
Is it possible to allow updating a guest entry? In the Craft 2 version this was possible like this, but wasn't in the core plugin either:

https://craftcms.stackexchange.com/questions/17414/update-form-entry-using-the-guest-entries-plugin

I know that's not a very secure way so maybe make it required to hash the id or something?

**Comment by angrybrad** [comment]
Not in our version of the plugin, but you can fork it and do whatever you want.  It would be nearly identical to the Craft 2 version, just updated with Craft 3 syntax. https://github.com/craftcms/docs

Yes, it's not secure because you're essentially allowing any anonymous user to edit those entries. Hashing wouldn't solve it because you can still see the original value... it's good for verifying that hashed data isn't tampered with on submit.  Your forked plugin could encrypt/decrypt the data, but you'd probably want some other logic to deter people from guessing element IDs since they are sequential and easy to test.
